spring:
  cache:
    type: caffeine
    caffeine:
      spec: expireAfterWrite=30s
  webflux:
    base-path: /moex-stock-api
moex:
  api:
    shares:
      url: "https://iss.moex.com/iss/engines/stock/markets/shares/boards/TQBR/securities"
      defaultCurrency: RUR
