spring:
  application:
    name: moex-stock-api-service
  cache:
    type: caffeine
  webflux:
    base-path: /moex-stock-api
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      username: rootuser
      password: rootpass
      database: moex-stock-api-db
caching:
  cacheNames:
    marketData:
      timeout: 5 # in seconds
    closedStockPrice:
      timeout: 60
    tickers:
      timeout: 86400 # 1 day
    baseInfo:
      timeout: 86400 # 1 day
moex:
  api:
    shares:
      defaultCurrency: RUR
feign-services:
  moex-stocks-endpoint: "https://iss.moex.com/iss/engines/stock/markets/shares/boards/TQBR/securities"
  moex-tickers-endpoint: "https://iss.moex.com/iss/engines/stock/markets/shares/boardgroups/57/securities"
#logging:
#  level:
#    reactivefeign.client.log: DEBUG
reactor:
  netty:
    tcp:
      sslHandshakeTimeout: 100000